# Debug statement to verify USER
- name: Check current user
  debug:
    msg: "Current user: {{ lookup('env', 'USER') }}"

# git
# vim
- import_tasks: vim.yml
  #when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

# apt
# zsh
- import_tasks: zsh.yml

# brew
- import_tasks: homebrew.yml
  tags: [homebrew]

# python (pyenv installs)
# rust
# system76
