# Copy .vimrc config to $HOME
- name: Copying VIM config to $HOME
  become: false
  copy:
    src: "vim/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}"
    owner: "{{ lookup('env', 'USER') }}"
    # group: "{{ lookup('env', 'USER') }}"  # linux only
    mode: 0644
    backup: yes
  with_items:
    - ".vimrc"
