[tool.poetry]
name = "bootstrap"
version = "0.1.0"
description = ""
authors = ["Dillon Stadther"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^8.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
